[package]
name = "simple-log"
version = "0.1.0"
authors = ["baoyachi <liaoymxsdl@gmail.com>"]
description = "A simple log"
edition = "2018"
keywords = ["log", "simple-log"]
readme = "README.md"
repository = "https://github.com/baoyachi/simple-log"
license = "MIT AND Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
