[package]
name = "simple-log"
version = "1.1.0"
authors = ["baoyachi <liaoymxsdl@gmail.com>"]
description = "A simple log"
edition = "2018"
keywords = ["log", "simple-log", "logger", "log4j", "log4rs"]
readme = "README.md"
categories = ["development-tools::debugging"]
documentation = "https://docs.rs/simple-log"
repository = "https://github.com/baoyachi/simple-log"
license = "MIT AND Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
log4rs = "0.13.0"
once_cell = "1.5.2"
serde = { version = "1.0.117", features = ["derive"] }
shadow-rs = { version = "0.7", optional = true, default-features = false }

[dev-dependencies]
serde_json = "1"
toml = "0.5.7"
serde_yaml = "0.8"