[package]
name = "simple-log"
version = "0.3.0"
authors = ["baoyachi <liaoymxsdl@gmail.com>"]
description = "A simple log"
edition = "2018"
keywords = ["log", "simple-log","logger","log4j","log4rs"]
readme = "README.md"
repository = "https://github.com/baoyachi/simple-log"
license = "MIT AND Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
log4rs = "0.13.0"